### ISSUE TITLE
DataHelper does not show options to select for row and column

### ISSUE THREAD

**Issue by evangeline85** [JelteMX/mendix-dynamic-table#2]
I mostly copied the domainmodel etc for this widget, but when I try to configure the datahelper  I do get selectoptions for the reference: context (also the ones I need for row and column), but for 'reference: Row' and 'reference: Column' I only see the nonpersistant EntryHelper object. I have no idea what is the difference between them. Is this a bug or do I miss something?

**Comment by JelteMX** [comment]
Can you show me a screenshot of the domain model? At least the relevant associations from EntryHelper to Row and Column? Seems to me that one might be missing.

**Comment by JelteMX** [comment]
I attached the latest version of my test-project to an issue that I will keep open. That might help. See [https://github.com/JelteMX/mendix-dynamic-table/issues/3](https://github.com/JelteMX/mendix-dynamic-table/issues/3)

**Comment by evangeline85** [comment]
Hey Jelte,

The weird thing is they are missing for both. No reference to select at all
for row or column. I already tried to place the row and the column entity
in the same module as the entryhelper and view, but it made no difference.
For context all three (view, column and row) are present for selection. The
domainmodel is added as the attachment.

Gr. Evangeline


Op do 13 feb. 2020 om 10:05 schreef Jelte Lagendijk <
notifications@github.com>:

**Comment by JelteMX** [comment]
Unfortunately attachment are not uploaded when you reply via e-mail. Can you add this manually on Github to this issue?

**Comment by evangeline85** [comment]
[DomeinModelRapportage.docx](https://github.com/JelteMX/mendix-dynamic-table/files/4198686/DomeinModelRapportage.docx)

**Comment by JelteMX** [comment]
So based on your input, I see the following.

For Entry Helper ([this screen](https://github.com/JelteMX/mendix-dynamic-table/blob/master/assets/settings5.png)) you will need to set the entity to EntryHelper, and then you should be able to set the correct references to both the EntryHelper_Column/Column and EntryHelper_Row/Row.

What I am missing here is what the Entry is in your case. That object should have a reference to both the Column as well as the Row. 

I strongly urge you to download my test-project, see [this link](https://github.com/JelteMX/widget-test-projects#matrix-widget) (click on Project MPK -> Download). That project might shed some light on how I structured this.

**Comment by evangeline85** [comment]
We found the problem. It is necessary to have a multiple to multiple association between EntryHelper and row/column to be able to choose them. Thank you for trying to help us.
