### ISSUE TITLE
Wrong parameter to event handlers

### ISSUE THREAD

**Issue by MiroslavSamoilenko** [JelteMX/mendix-dynamic-table#7]
Micro flow and nanoflow handlers for matrix column receive an empty Entry parameter instead of the Column parameter.

**Comment by JelteMX** [comment]
I see it in the code.... My bad! I will release a new version soon

**Comment by MiroslavSamoilenko** [comment]
Please, check both columns and rows, nano and micro flows. Just in case :-)

**Comment by JelteMX** [comment]
Fixed in [1.3.2](https://github.com/JelteMX/mendix-dynamic-table/releases/tag/1.3.2), released in the App Store. Thanks for reporting!
