### ISSUE TITLE
Does not work for 'large' amounts of data

### ISSUE THREAD

**Issue by EvyK** [JelteMX/mendix-dynamic-table#9]
Is there a max number of entries that can be used? It does work fine with 150 or something, but when I tried about 1000 entries it fails to generate.

**Comment by JelteMX** [comment]
There shouldn't be a max i think, although it can become a performance issue at some point. If you can show me an example on where it fails I could investigate. You could contact me on jelte.lagendijk{at}mendix.com if you have a test-project

**Comment by JelteMX** [comment]
OK, some good news. I have managed to find the biggest issue with table, making it rendering a lot faster.

Working on a fix. Currently testing with 1000 rows & 10 columns, resulting in 10.000+ objects. Still renders, but still takes about 15 seconds to render.

**Comment by JelteMX** [comment]
Version [1.3.3](https://github.com/JelteMX/mendix-dynamic-table/releases/tag/1.3.3) is released in the App Store, this should fix issues with 'large' datasets. 

I was still able to render 10.000 objects, obviously it gets progressively slower and slower. When trying 100.000 objects the browser was slowly eating away my computer, settings my CPU on fire and consuming large amounts of RAM. There are limitations....
